### PR TITLE
Add support for "using NFTs"

### PR DESCRIPTION
**Pull request by kyrelldixon**
Hey @lorisleiva ! I created this draft PR to start getting some feedback on the uses implementation I'm working on.

This adds support for "using" an NFT based on the Utilize instruction mentioned in the [Metaplex docs](https://docs.metaplex.com/programs/token-metadata/instructions#reduce-the-number-of-uses), and closes issue #101  It currently only supports the `owner` of the NFT being allowed to decrement the uses, so there will need to be more support for handling a `useAuthority`.

Work that's left:
- [ ] Add documentation for `uses` to the README
- [ ] Add more unit tests for different edge cases
- [ ] Support a `useAuthority` through a `useAuthorityRecord`
- [ ] Support a `burner`
- [ ] Improve error handling for misused (no pun intended) NFTs

### CODE REVIEW

**Comment by lorisleiva** [comment]
Hey @kyrelldixon 👋 

So, first of all, a massive thank you for taking the time to start this PR.

Unfortunately, there's two pieces of information you couldn't know about that affect this significantly. I apologise for not being able to communicate that better on GitHub.

- I'm currently working on a big refactor of the NFT module so it is consistent with the latest (non-documented) modules. That is going to change your implementation quite a lot so I suggest pausing what you're doing. The refactor PR should drop hopefully today but maybe tomorrow.
- The other big thing is that we have got some fellows (like interns) working at Metaplex and they have been assigned some of these issues (see the "fellowship" label on the original issue). One of these fellows is actually already working on this issue and waiting for my refactoring PR to be merged.

Soon I will be able to better document these tasks in advance so this situation doesn't happen again. Sorry about that.

**Comment by kyrelldixon** [comment]
> Hey @kyrelldixon 👋
> 
> So, first of all, a massive thank you for taking the time to start this PR.
> 
> Unfortunately, there's two pieces of information you couldn't know about that affect this significantly. I apologise for not being able to communicate that better on GitHub.
> 
> * I'm currently working on a big refactor of the NFT module so it is consistent with the latest (non-documented) modules. That is going to change your implementation quite a lot so I suggest pausing what you're doing. The refactor PR should drop hopefully today but maybe tomorrow.
> * The other big thing is that we have got some fellows (like interns) working at Metaplex and they have been assigned some of these issues (see the "fellowship" label on the original issue). One of these fellows is actually already working on this issue and waiting for my refactoring PR to be merged.
> 
> Soon I will be able to better document these tasks in advance so this situation doesn't happen again. Sorry about that.

Thanks for the update @lorisleiva! I wasn't aware of what the `fellowship` tag meant, so that's good to know for future reference. I'm planning on uses this for a Pointer tutorial, so looking forward to it being merged! I'll go ahead and close this.

**Comment by lorisleiva** [comment]
Just a quick update: The refactoring has been merged. 👌

**Comment by kyrelldixon** [comment]
> Just a quick update: The refactoring has been merged. 👌

Awesome! Any updates on when `uses` will be available?

**Comment by lorisleiva** [comment]
It is live as of `v0.12.2`. 🚀

**Pull request closed without merging**
