### PR TITLE
feat: :sparkles: plugins: Transition from Bundlr to Irys storage driver

### PR DESCRIPTION
**Pull request by JesseTheRobot**
Context: Bundlr rebranded as Irys earlier today, and the GH org rename caused [issues with users](https://discord.com/channels/848060988636921856/849844496941842432/1159172249249648771) due to the AVSC git dependency the old version of the js-client being used. 
To fix this, this PR transitions from a deprecated Bundlr js sdk version to the latest Irys SDK, and includes all relevant changes/renaming, including README & test changes.

Note: I wasn't able to figure out how to get most test cases to pass, I assume there's a testing endpoint I need to set up - but all the tests I was able to get working pass.

### CODE REVIEW

**Comment by YvesCandel** [comment]
We're also experiencing the issue, so this would be great 👍

**Comment by justinkchen** [comment]
what is the fixed git repo URL supposed to be? I'm also getting this issue and when I did a `pnpm up` it didn't seem to fix the issue

**Comment by justinkchen** [comment]
i've tried `pnpm up` it still keeps the same package in the pnpm lockfile. any othre suggestions?

**Comment by justinkchen** [comment]
@JesseTheRobot that did it! thanks!

**Review by lorisleiva — APPROVED** [review]
Thanks for that! I no longer have the rights to trigger CI but if it passes I think it's okay to merge. Note that here it's okay replace the Bundlr package (as opposed to in Umi) because here everything is bundled together so we want to avoid adding too many dependencies.

**Comment by lorisleiva** [comment]
Thanks! Cc @febo would you mind just pressing the button to approve CI?

**Comment by lorisleiva** [comment]
`pnpm lint:fix` should do the trick.

**Comment by lorisleiva** [comment]
Hmm if it's just a linting issue I'm happy to merge it as-is. The main workflow will automatically create a fix commit when merged. I'm not at Metaplex anymore so I don't have the rights to merge but maybe @febo can do the honours?

**Review by lorisleiva — APPROVED** [review]

**Review by febo — APPROVED** [review]

**Pull request merged**
